name: RepoPulse: Commit Count Tracker

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get Commit Count
      run: |
        COMMIT_COUNT=$(git rev-list --count HEAD)
        echo "RepoPulse Commit Count: $COMMIT_COUNT"
        sed -i "s/commit_count_placeholder/$COMMIT_COUNT/g" README.md

    - name: Commit Updated README
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"
        git add README.md
        git commit -m "Update RepoPulse README with commit count"
        git push
